class ReferenciasImagens():

   

  
    def getArrayReferencia(self):

       '''Array de imagens dos remedios'''
        imagensDrogasAlprazolam = ['imagens remedio\\Alprazolam\\3089_lg.jpg',
                                       'imagens remedio\\Alprazolam\\3283_lg.jpg',
                                       'imagens remedio\\Alprazolam\\3310_lg.jpg',
                                       'imagens remedio\\Alprazolam\\3527_lg.jpg',
                                       'imagens remedio\\Alprazolam\\3632_lg.jpg',
                                       'imagens remedio\\Alprazolam\\3665_lg.jpg',
                                       'imagens remedio\\Alprazolam\\3987_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4005_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4035_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4047_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4065_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4282_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4493_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4550_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4734_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4751_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4752_lg.jpg',
                                       'imagens remedio\\Alprazolam\\4887_lg.jpg',
                                       'imagens remedio\\Alprazolam\\5041_lg.jpg',
                                       'imagens remedio\\Alprazolam\\5045_lg.jpg']
    
        imagensDrogasDomino = ['imagens remedio\\Domino\\3117_lg.jpg',
                               'imagens remedio\\Domino\\3303_lg.jpg',
                               'imagens remedio\\Domino\\3642_lg.jpg',
                               'imagens remedio\\Domino\\3654_lg.jpg',
                               'imagens remedio\\Domino\\3761_lg.jpg',
                               'imagens remedio\\Domino\\3896_lg.jpg',
                               'imagens remedio\\Domino\\4424_lg.jpg',
                               'imagens remedio\\Domino\\4461_lg.jpg',
                               'imagens remedio\\Domino\\4470_lg.jpg',
                               'imagens remedio\\Domino\\4569_lg.jpg',
                               'imagens remedio\\Domino\\4570_lg.jpg',
                               'imagens remedio\\Domino\\4571_lg.jpg',
                               'imagens remedio\\Domino\\4572_lg.jpg',
                               'imagens remedio\\Domino\\4805_lg.jpg',
                               'imagens remedio\\Domino\\4840_lg.jpg',
                               'imagens remedio\\Domino\\5130_lg.jpg']  
    
        imagensDrogasMediumCut = ['imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg',
                                  'imagens remedio\\Domino\\3117_lg.jpg']



