class ReferenciasImagens():
     
     alprazolam = ['imagens remedio\\Alprazolam\\3089_lg.jpg',
                      'imagens remedio\\Alprazolam\\3283_lg.jpg',
                      'imagens remedio\\Alprazolam\\3310_lg.jpg',
                      'imagens remedio\\Alprazolam\\3527_lg.jpg',
                      'imagens remedio\\Alprazolam\\3632_lg.jpg',
                      'imagens remedio\\Alprazolam\\3665_lg.jpg',
                      'imagens remedio\\Alprazolam\\3987_lg.jpg',
                      'imagens remedio\\Alprazolam\\4005_lg.jpg',
                      'imagens remedio\\Alprazolam\\4035_lg.jpg',
                      'imagens remedio\\Alprazolam\\4047_lg.jpg',
                      'imagens remedio\\Alprazolam\\4065_lg.jpg',
                      'imagens remedio\\Alprazolam\\4282_lg.jpg',
                      'imagens remedio\\Alprazolam\\4493_lg.jpg',
                      'imagens remedio\\Alprazolam\\4550_lg.jpg',
                      'imagens remedio\\Alprazolam\\4734_lg.jpg',
                      'imagens remedio\\Alprazolam\\4751_lg.jpg',
                      'imagens remedio\\Alprazolam\\4752_lg.jpg',
                      'imagens remedio\\Alprazolam\\4887_lg.jpg',
                      'imagens remedio\\Alprazolam\\5041_lg.jpg',
                      'imagens remedio\\Alprazolam\\5045_lg.jpg']  
     domino = ['imagens remedio\\Domino\\3117_lg.jpg',
               'imagens remedio\\Domino\\3303_lg.jpg',
               'imagens remedio\\Domino\\3642_lg.jpg',
               'imagens remedio\\Domino\\3654_lg.jpg',
               'imagens remedio\\Domino\\3761_lg.jpg',
               'imagens remedio\\Domino\\3896_lg.jpg',
               'imagens remedio\\Domino\\4424_lg.jpg',
               'imagens remedio\\Domino\\4461_lg.jpg',
               'imagens remedio\\Domino\\4470_lg.jpg',
               'imagens remedio\\Domino\\4569_lg.jpg',
               'imagens remedio\\Domino\\4570_lg.jpg',
               'imagens remedio\\Domino\\4571_lg.jpg',
               'imagens remedio\\Domino\\4572_lg.jpg',
               'imagens remedio\\Domino\\4805_lg.jpg',
               'imagens remedio\\Domino\\4840_lg.jpg',
               'imagens remedio\\Domino\\5130_lg.jpg']
     mediumCut = ['imagens remedio\\Medium Cut\\3026_lg.jpg',
                  'imagens remedio\\Medium Cut\\3088_lg.jpg',
                  'imagens remedio\\Medium Cut\\3092_lg.jpg',
                  'imagens remedio\\Medium Cut\\3095_lg.jpg',
                  'imagens remedio\\Medium Cut\\3101_lg.jpg',
                  'imagens remedio\\Medium Cut\\3111_lg.jpg',
                  'imagens remedio\\Medium Cut\\3118_lg.jpg',
                  'imagens remedio\\Medium Cut\\3174_lg.jpg',
                  'imagens remedio\\Medium Cut\\3193_lg.jpg',
                  'imagens remedio\\Medium Cut\\3259_lg.jpg',
                  'imagens remedio\\Medium Cut\\3328_lg.jpg',
                  'imagens remedio\\Medium Cut\\3337_lg.jpg',
                  'imagens remedio\\Medium Cut\\3344_lg.jpg',
                  'imagens remedio\\Medium Cut\\3469_lg.jpg',
                  'imagens remedio\\Medium Cut\\3471_lg.jpg',
                  'imagens remedio\\Medium Cut\\3477_lg.jpg',
                  'imagens remedio\\Medium Cut\\3500_lg.jpg',
                  'imagens remedio\\Medium Cut\\3508_lg.jpg',
                  'imagens remedio\\Medium Cut\\3720_lg.jpg',
                  'imagens remedio\\Medium Cut\\3723_lg.jpg',
                  'imagens remedio\\Medium Cut\\3739_lg.jpg',
                  'imagens remedio\\Medium Cut\\3767_lg.jpg',
                  'imagens remedio\\Medium Cut\\3829_lg.jpg',
                  'imagens remedio\\Medium Cut\\3989_lg.jpg',
                  'imagens remedio\\Medium Cut\\4083_lg.jpg',
                  'imagens remedio\\Medium Cut\\4085_lg.jpg',
                  'imagens remedio\\Medium Cut\\4207_lg.jpg',
                  'imagens remedio\\Medium Cut\\4442_lg.jpg',
                  'imagens remedio\\Medium Cut\\4541_lg.jpg',
                  'imagens remedio\\Medium Cut\\4607_lg.jpg',
                  'imagens remedio\\Medium Cut\\4857_lg.jpg',
                  'imagens remedio\\Medium Cut\\5014_lg.jpg',
                  'imagens remedio\\Medium Cut\\5015_lg.jpg',
                  'imagens remedio\\Medium Cut\\5036_lg.jpg',
                  'imagens remedio\\Medium Cut\\5057_lg.jpg',
                  'imagens remedio\\Medium Cut\\5195_lg.jpg',
                  'imagens remedio\\Medium Cut\\5202_lg.jpg']
     tesla = ['imagens remedio\\Tesla\\3558_lg.jpg',
              'imagens remedio\\Tesla\\3589_lg.jpg',
              'imagens remedio\\Tesla\\3656_lg.jpg',
              'imagens remedio\\Tesla\\3682_lg.jpg',
              'imagens remedio\\Tesla\\3784_lg.jpg',
              'imagens remedio\\Tesla\\3855_lg.jpg',
              'imagens remedio\\Tesla\\3973_lg.jpg',
              'imagens remedio\\Tesla\\4004_lg.jpg',
              'imagens remedio\\Tesla\\4171_lg.jpg',
              'imagens remedio\\Tesla\\4329_lg.jpg',
              'imagens remedio\\Tesla\\4430_lg.jpg',
              'imagens remedio\\Tesla\\4487_lg.jpg',
              'imagens remedio\\Tesla\\4506_lg.jpg',
              'imagens remedio\\Tesla\\4557_lg.jpg',
              'imagens remedio\\Tesla\\4598_lg.jpg',
              'imagens remedio\\Tesla\\4606_lg.jpg',
              'imagens remedio\\Tesla\\4619_lg.jpg',
              'imagens remedio\\Tesla\\4721_lg.jpg',
              'imagens remedio\\Tesla\\4759_lg.jpg',
              'imagens remedio\\Tesla\\4772_lg.jpg',
              'imagens remedio\\Tesla\\4773_lg.jpg',
              'imagens remedio\\Tesla\\4885_lg.jpg',
              'imagens remedio\\Tesla\\4904_lg.jpg',
              'imagens remedio\\Tesla\\4913_lg.jpg',
              'imagens remedio\\Tesla\\5056_lg.jpg',
              'imagens remedio\\Tesla\\5086_lg.jpg']
     warnerBros = ['imagens remedio\\Tesla\\3291_lg.jpg',
                   'imagens remedio\\Tesla\\3299_lg.jpg',
                   'imagens remedio\\Tesla\\3634_lg.jpg',
                   'imagens remedio\\Tesla\\3912_lg.jpg',
                   'imagens remedio\\Tesla\\3952_lg.jpg',
                   'imagens remedio\\Tesla\\3981_lg.jpg',
                   'imagens remedio\\Tesla\\4013_lg.jpg',
                   'imagens remedio\\Tesla\\4020_lg.jpg',
                   'imagens remedio\\Tesla\\4198_lg.jpg',
                   'imagens remedio\\Tesla\\4219_lg.jpg',
                   'imagens remedio\\Tesla\\4254_lg.jpg',
                   'imagens remedio\\Tesla\\4453_lg.jpg',
                   'imagens remedio\\Tesla\\4590_lg.jpg',
                   'imagens remedio\\Tesla\\4748_lg.jpg',
                   'imagens remedio\\Tesla\\4894_lg.jpg',
                   'imagens remedio\\Tesla\\4992_lg.jpg',
                   'imagens remedio\\Tesla\\5002_lg.jpg',
                   'imagens remedio\\Tesla\\5003_lg.jpg']

       
        